### PR TITLE
Do-block in `mktemp` in `_find_ambiguities`

### PR DESCRIPTION
**Pull request by jishnub**
The do-block form ensures that the files are automatically closed

### CODE REVIEW

**Review by lgoettgens — APPROVED** [review]

**Comment by lgoettgens** [comment]
Thanks for the PR! I didn't think about this when working on #166.

@fingolfin this change should be backported to 0.6.x

**Comment by lgoettgens** [comment]
> @fingolfin this change should be backported to 0.6.x

Bump

**Comment by fingolfin** [comment]
I have no interest in investing time in maintaining the 0.6.x branch; and this is a tiny annoyance at best, not a serious bug fix

**Comment by lgoettgens** [comment]
> I have no interest in investing time in maintaining the 0.6.x branch; and this is a tiny annoyance at best, not a serious bug fix

ok, that's a decision I am more than fine with

**Pull request merged**
