### PR TITLE
Refactor `ambiguities.jl`

### PR DESCRIPTION
**Pull request by lgoettgens**
Changes:

- Formatting, it annoys me every time I want to change something that I cannot run the autoformatter
- Parse the output of `test_ambiguities_impl` to allow better testing (number of ambiguities and errors inside `getobj`)
- Adapt the tests

### CODE REVIEW

**Comment by devmotion** [comment]
> Formatting, it annoys me every time I want to change something that I cannot run the autoformatter

I guess the style should be defined in a `.JuliaFormatter.toml` file?

**Comment by lgoettgens** [comment]
> > Formatting, it annoys me every time I want to change something that I cannot run the autoformatter
> 
> I guess the style should be defined in a `.JuliaFormatter.toml` file?

This project is mostly using the default style

**Comment by devmotion** [comment]
Which default style? IIRC, e.g., VSCode requires a `.JuliaFormatter.toml` and does not support any global or default options. Generally, it also seems safer to fix a style instead of relying on local settings of developers.

**Comment by lgoettgens** [comment]
> Which default style? IIRC, e.g., VSCode requires a `.JuliaFormatter.toml` and does not support any global or default options. Generally, it also seems safer to fix a style instead of relying on local settings of developers.

I am using VSCode with an empty `.JuliaFormatter.toml`. This then falls back to some defaults defined in `JuliaFormatter.jl`.
But I agree with you, that we should add a `.JuliaFormatter.toml` to `Aqua`, but not in this PR.

**Comment by devmotion** [comment]
> I am using VSCode with an empty .JuliaFormatter.toml

But that's your setting and someone else might use different options :slightly_smiling_face: 

> But I agree with you, that we should add a .JuliaFormatter.toml to Aqua, but not in this PR.

IMO formatting changes due to the autoformatter are better motivated if the style is clearly fixed. Otherwise someone else might open another PR with formatting changes based on different style options :slightly_smiling_face:

**Comment by fingolfin** [comment]
This now needs a rebase.

**Comment by lgoettgens** [comment]
This is now rebased. The formatting commit now only contains two minor changes, where I made the code a bit more readable and shorter compared to the formatter.

**Pull request merged**
