### PR TITLE
Make CI jobs runable by hand

### PR DESCRIPTION
**Pull request by lgoettgens**
to be able to run the documentation build for all skipped versions (cf. #182)

### CODE REVIEW

**Comment by fingolfin** [comment]
So what's the plan now? Manually re-run the workflow first for the v0.6.6 tag; then once that completed and hopefully updated the website, do the same for v0.7.1 ?

**Comment by fingolfin** [comment]
Sounds good, please go ahead :-)

**Comment by hyrodium** [comment]
>I will release a v0.6.7 and we hope everything works then by itself. 

The documentation for `v0.6.7` is deployed correctly! :tada: 
https://juliatesting.github.io/Aqua.jl/v0.6.7/

**Comment by lgoettgens** [comment]
> > I will release a v0.6.7 and we hope everything works then by itself.
> 
> The documentation for `v0.6.7` is deployed correctly! 🎉 https://juliatesting.github.io/Aqua.jl/v0.6.7/

Yeah 🎉
I will do a v0.7.x release next.

**Pull request merged**
